# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4789e02c4175deb2a59349c1d336db357cf18d46edec07e4ffbc2fb230cd3cf8cb2854c5137dc2a606daf3eaf31b829ff0dbdd0b3d82ad3776bb59f59478700a

test:
  secret_key_base: 5b1a7bf489c6f221a67a83e4181ebfb547bd3a8fe1cb9c1cf784e00feb424693c524677e2165f4ad5197a9dc8159b3dd1ff6eb685120c615e054097134da8897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
